http://mobile.lemonde.fr/politique/?xtref=acc_dir
https://fr.m.wikipedia.org/wiki/Politique
http://m.nouvelobs.com/politique/
http://www.lepoint.fr/politique/
http://www.bfmtv.com/politique/
https://fr.news.yahoo.com/politique/
http://www.liberation.fr/france,11
http://www.lejdd.fr/Politique
http://www.lexpress.fr/actualite/politique/