http://m.youtube.com/watch?v=wQP9XZc2Y_c
http://m.youtube.com/watch?v=z7mEF7gRGik
http://m.youtube.com/watch?v=QxmLKgM6Sbc
http://www.allocine.fr/film/fichefilm_gen_cfilm=203691.html
http://www.disney.fr/films/la-reine-des-neiges
https://fr.m.wikipedia.org/wiki/La_Reine_des_neiges_(film,_2013)
http://www.disneystore.fr/la-reine-des-neiges/mn/1435501/
http://www.cdiscount.com/juniors/heros-et-supers-heros-2/la-reine-des-neiges/l-1207319.html
http://m.telestar.fr/2016/photos/la-reine-des-neiges2-la-date-de-sortie-enfin-annoncee!-photos-191397
http://streamcomplet.com/la-reine-des-neiges/